name: Build APK (Docker, non-interactive)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer (auto-confirm root)
        run: |
          docker run --rm \
            -v $PWD:/home/user/app \
            -w /home/user/app \
            -e BUILDOZER_ALLOW_ROOT=1 \
            kivy/buildozer \
            bash -c "export PATH=\$PATH:/home/user/.local/bin && buildozer -v android debug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-time-apk
          path: bin/*.apk





