name: Build Python APK with Buildozer (Auto Root Accept)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK using Docker
        run: |
          docker run --rm \
            -e BUILDOZER_ALLOW_ROOT=1 \
            -v $PWD:/home/user/app \
            -w /home/user/app \
            kivy/buildozer \
            bash -c "buildozer -v android debug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-time-apk
          path: bin/*.apk






