name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK (auto-confirm root)
        run: |
          docker run --rm \
            -v $PWD:/home/user/app \
            -w /home/user/app \
            kivy/buildozer \
            bash -c "yes | buildozer -v android debug"
      - uses: actions/upload-artifact@v4
        with:
          name: password-time-apk
          path: bin/*.apk







