name: Build APK (Docker)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer (no root prompt)
        run: |
          docker run --rm -u 1000:1000 -v $PWD:/home/user/app kivy/buildozer \
            bash -c "export PATH=\$PATH:/home/user/.local/bin && buildozer -v android debug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-time-apk
          path: bin/*.apk



